name: Bug report
description: Reporting an issue
labels: ["bug"]
body:
  - type: dropdown
    attributes:
      label: Operating System
      description: On which operating system do you have a problem?
      options:
        - Windows
        - MacOS
        - Linux
        - Android
        - IOS
        - Other
    validations:
      required: true
  - type: input
    attributes:
      label: Other
      description: What is your operating system (for people how choose Other)?
    validations:
      required: false
  - type: input
    attributes:
      label: Web Browser
      description: On which web browser do you have a problem?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Issue description
      description: A short description of the issue
    validations:
      required: true
