on: [push]
name: Commit preview

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    name: Generate commit preview
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Enable Corepack shims
        run: corepack enable

      - name: Install dependencies
        run: pnpm install

      - name: Build the project
        run: pnpm build

      - name: Publish to Pages
        uses: cloudflare/pages-action@1
        id: publish
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: developer-wiki-test
          directory: build

      - name: Add a comment on the commit
        uses: peter-evans/commit-comment@v1
        with:
          token: ${{ secrets.COZY_PAT }}
          repository: ${{ github.repository }}
          sha: ${{ github.sha }}
          body: "See preview on Cloudflare Pages: ${{ steps.publish.outputs.url }}"
