on: [pull_request]
name: PR preview

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    name: Generate PR preview
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack shims
        run: corepack enable

      - name: Install dependencies
        run: pnpm install

      - name: Build the project
        run: pnpm build

      - name: Upload HTML artifact
        uses: actions/upload-artifact@v4
        with:
          name: website-html
          path: build
          retention-days: 1
